apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: myprofile-secretstore
    kind: SecretStore
  target:
    name: myprofile-db-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: app/dev/database/env