---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprofile-frontend
spec:
  selector:
    matchLabels:
      app: myprofile-frontend
  template:
    metadata:
      labels:
        app: myprofile-frontend
    spec:
      containers:
        - name: myprofile-frontend
          image: 139080726045.dkr.ecr.us-east-1.amazonaws.com/frontend:aae63f030dc9b113c6beb383becd3e7fd1f9b035
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: myprofile-frontend-env-config