---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myprofile-backend
spec:
  selector:
    matchLabels:
      app: myprofile-backend
  template:
    metadata:
      labels:
        app: myprofile-backend
    spec:
      initContainers:
        - name: myprofile-backend-migration
          # image: cl0ud/myprofile-be:1.0.0
          image: 139080726045.dkr.ecr.us-east-1.amazonaws.com/gitops:b769ed405899859dfbdc89530a17f7115a8b9dab
          command: ['sh', '-c', 'php artisan migrate:fresh --seed']
          envFrom:
            - configMapRef:
                name: myprofile-backend-env-config

      containers:
        - name: myprofile-backend
          image: 139080726045.dkr.ecr.us-east-1.amazonaws.com/gitops:b769ed405899859dfbdc89530a17f7115a8b9dab
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: myprofile-backend-env-config