---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      initContainers:
        - name: todo-migration
          image: 139080726045.dkr.ecr.us-east-1.amazonaws.com/gitops/af87a2c57b45a012699866004914e3f56c180cca
          command: ['sh', '-c', 'php artisan migrate:fresh']
          envFrom:
            - configMapRef:
                name: todo-env-config

      containers:
        - name: todo
          image: 139080726045.dkr.ecr.us-east-1.amazonaws.com/gitops/af87a2c57b45a012699866004914e3f56c180cca
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: todo-env-config
        