resources:
  - database.yaml
  - redis.yaml
  - deployment-be.yaml
  - service-be.yaml
  - deployment-fe.yaml
  - service-fe.yaml 

configMapGenerator:
  - name: myprofile-backend-env-config
    envs:
      - .backend.env
  - name: myprofile-frontend-env-config
    envs:
      - .frontend.env      
  - name: myprofile-db-config
    envs:
      - .database.env